import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: {
    backgroundColor: '#F5F5F5',
    flex: 1,
  },
  content: {
    flexGrow: 1,
    paddingBottom: 28,
    paddingHorizontal: 20,
  },
  centeredState: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    padding: 24,
  },
  loadingText: {
    color: '#605C5E',
    fontFamily: 'Monda_400Regular',
    fontSize: 13,
    marginTop: 12,
  },
  designHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    minHeight: 74,
  },
  headerCopy: {
    flex: 1,
    marginHorizontal: 8,
  },
  designHeading: {
    color: '#262224',
    fontFamily: 'Monda_700Bold',
    fontSize: 22,
  },
  designSupporting: {
    color: '#605C5E',
    fontFamily: 'Monda_400Regular',
    fontSize: 10,
  },
  profileButton: {
    alignItems: 'center',
    borderColor: '#262224',
    borderRadius: 18,
    borderWidth: 1,
    height: 35,
    justifyContent: 'center',
    overflow: 'hidden',
    width: 35,
  },
  listNameInput: {
    backgroundColor: '#FFFFFF',
    borderColor: '#D1CFD0',
    borderRadius: 6,
    borderWidth: 1,
    color: '#262224',
    fontFamily: 'Monda_700Bold',
    fontSize: 14,
    marginBottom: 10,
    minHeight: 44,
    paddingHorizontal: 12,
  },
  searchInputRow: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#9A9899',
    borderRadius: 6,
    borderWidth: 1,
    flexDirection: 'row',
    minHeight: 44,
    paddingHorizontal: 12,
  },
  designInput: {
    color: '#262224',
    flex: 1,
    fontFamily: 'Monda_400Regular',
    fontSize: 12,
    marginLeft: 8,
  },
  plus: {
    color: '#258043',
    fontSize: 25,
    lineHeight: 28,
  },
  suggestions: {
    backgroundColor: '#FFFFFF',
    borderColor: '#D1CFD0',
    borderRadius: 6,
    borderWidth: 1,
    marginTop: 6,
    overflow: 'hidden',
  },
  suggestion: {
    alignItems: 'center',
    borderBottomColor: '#E3E1E2',
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 38,
    paddingHorizontal: 12,
  },
  suggestionName: {
    color: '#262224',
    fontFamily: 'Monda_700Bold',
    fontSize: 11,
  },
  suggestionDetails: {
    color: '#767274',
    fontFamily: 'Monda_400Regular',
    fontSize: 10,
  },
  designListCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#D1CFD0',
    borderRadius: 6,
    borderWidth: 1,
    marginTop: 13,
    overflow: 'hidden',
  },
  listHeader: {
    alignItems: 'center',
    borderBottomColor: '#D1CFD0',
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 39,
    paddingHorizontal: 13,
  },
  listTitle: {
    color: '#262224',
    fontFamily: 'Monda_700Bold',
    fontSize: 13,
  },
  clearAll: {
    color: '#35824B',
    fontFamily: 'Monda_400Regular',
    fontSize: 10,
  },
  itemRow: {
    alignItems: 'center',
    borderBottomColor: '#E3E1E2',
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    minHeight: 42,
    paddingHorizontal: 13,
  },
  checkbox: {
    alignItems: 'center',
    borderColor: '#258043',
    borderRadius: 4,
    borderWidth: 1.5,
    height: 18,
    justifyContent: 'center',
    marginRight: 10,
    width: 18,
  },
  checkboxChecked: { backgroundColor: '#258043' },
  checkmark: { color: '#FFFFFF', fontFamily: 'Monda_700Bold', fontSize: 12, lineHeight: 14 },
  itemName: {
    color: '#262224',
    flex: 1,
    fontFamily: 'Monda_400Regular',
    fontSize: 12,
  },
  itemPrice: {
    color: '#767274',
    fontFamily: 'Monda_400Regular',
    fontSize: 10,
    marginHorizontal: 10,
    textAlign: 'center',
  },
  editText: {
    color: '#35824B',
    fontFamily: 'Monda_700Bold',
    fontSize: 9,
  },
  emptyList: {
    color: '#767274',
    fontFamily: 'Monda_400Regular',
    fontSize: 11,
    padding: 18,
    textAlign: 'center',
  },
  tipCard: {
    alignItems: 'center',
    backgroundColor: '#EEF3D0',
    borderRadius: 6,
    flexDirection: 'row',
    marginTop: 13,
    minHeight: 76,
    paddingHorizontal: 10,
  },
  tipText: {
    color: '#504C4E',
    flex: 1,
    fontFamily: 'Monda_400Regular',
    fontSize: 9,
    lineHeight: 14,
    marginLeft: 7,
  },
  tipStrong: {
    color: '#337845',
    fontFamily: 'Monda_700Bold',
  },
  unresolvedCard: {
    backgroundColor: '#FFF4E8',
    borderColor: '#E7A928',
    borderRadius: 6,
    borderWidth: 1,
    marginTop: 13,
    padding: 12,
  },
  unresolvedTitle: {
    color: '#262224',
    fontFamily: 'Monda_700Bold',
    fontSize: 12,
  },
  unresolvedText: {
    color: '#615D5F',
    fontFamily: 'Monda_400Regular',
    fontSize: 10,
    lineHeight: 15,
    marginTop: 2,
  },
  unresolvedRow: {
    alignItems: 'center',
    borderTopColor: '#E8D6C0',
    borderTopWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    marginTop: 8,
    paddingTop: 8,
  },
  unresolvedNameButton: {
    flex: 1,
  },
  unresolvedName: {
    color: '#262224',
    fontFamily: 'Monda_700Bold',
    fontSize: 11,
  },
  activeCard: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#D1CFD0',
    borderRadius: 6,
    borderWidth: 1,
    flexDirection: 'row',
    marginTop: 13,
    padding: 12,
  },
  activeCopy: {
    flex: 1,
    marginRight: 12,
  },
  activeTitle: {
    color: '#262224',
    fontFamily: 'Monda_700Bold',
    fontSize: 12,
  },
  activeDescription: {
    color: '#615D5F',
    fontFamily: 'Monda_400Regular',
    fontSize: 10,
    marginTop: 2,
  },
  activeSwitch: {
    backgroundColor: '#A6A3A4',
    borderRadius: 14,
    height: 28,
    justifyContent: 'center',
    padding: 2,
    width: 48,
  },
  activeSwitchOn: {
    backgroundColor: '#DFF0DD',
  },
  switchThumb: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    height: 24,
    width: 24,
  },
  switchThumbOn: {
    alignSelf: 'flex-end',
    backgroundColor: '#258043',
  },
  feedbackText: {
    color: '#B42318',
    fontFamily: 'Monda_400Regular',
    fontSize: 11,
    marginTop: 8,
  },
  actionRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 13,
  },
  button: {
    alignItems: 'center',
    borderRadius: 6,
    justifyContent: 'center',
    minHeight: 43,
    paddingHorizontal: 12,
  },
  buttonDisabled: {
    opacity: 0.45,
  },
  saveLaterButton: {
    backgroundColor: '#FFFFFF',
    borderColor: '#258043',
    borderWidth: 1,
    flex: 1,
  },
  saveLaterText: {
    color: '#258043',
    fontFamily: 'Monda_700Bold',
    fontSize: 11,
  },
  routeButton: {
    backgroundColor: '#258043',
    flex: 1,
  },
  buttonText: {
    color: '#FFFFFF',
    fontFamily: 'Monda_700Bold',
    fontSize: 11,
  },
  deleteButton: {
    alignItems: 'center',
    alignSelf: 'center',
    marginTop: 16,
    minHeight: 38,
    paddingHorizontal: 18,
  },
  deleteButtonText: {
    color: '#B42318',
    fontFamily: 'Monda_700Bold',
    fontSize: 11,
  },
});