import { StyleSheet } from 'react-native';

import { colors, fontFamily, radius, spacing } from '../theme';

export const styles = StyleSheet.create({
  screen: {
    backgroundColor: colors.surface,
    flex: 1,
  },
  screenHeader: {
    alignItems: 'center',
    borderBottomColor: colors.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    minHeight: 82,
    paddingHorizontal: spacing.lg,
  },
  backButton: {
    alignItems: 'center',
    height: 40,
    justifyContent: 'center',
    transform: [{ rotate: '-90deg' }],
    width: 32,
  },
  headerCopy: { flex: 1, marginLeft: spacing.sm, minWidth: 0 },
  headerSubtitle: { color: colors.textMuted, fontFamily: fontFamily.regular, fontSize: 13, lineHeight: 18, marginTop: 2 },
  profileButton: { alignItems: 'center', backgroundColor: '#E8F5BC', borderColor: colors.surface, borderRadius: 22, borderWidth: 2, height: 40, justifyContent: 'center', width: 44 },
  content: {
    padding: spacing.lg,
    paddingBottom: spacing.xl,
  },
  centeredState: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    padding: 24,
  },
  header: {
    marginBottom: 20,
  },
  title: {
    color: colors.text,
    fontFamily: fontFamily.bold,
    fontSize: 20,
    lineHeight: 27,
  },
  subtitle: {
    color: colors.textMuted,
    fontFamily: fontFamily.regular,
    fontSize: 13,
    lineHeight: 19,
  },
  routeModes: {
    marginBottom: 14,
    marginTop: 16,
  },
  routeCard: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radius.md,
    borderWidth: 1,
    marginBottom: 12,
    padding: 16,
  },
  routeCardSelected: {
    backgroundColor: colors.surfaceSubtle,
    borderColor: colors.primary,
    borderWidth: 2,
  },
  routeCardPressed: {
    opacity: 0.72,
  },
  routeCardHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  routeLabel: {
    color: colors.text,
    fontFamily: fontFamily.bold,
    fontSize: 17,
  },
  score: {
    color: colors.primary,
    fontFamily: fontFamily.bold,
    fontSize: 14,
  },
  metrics: {
    flexDirection: 'row',
    marginTop: 16,
  },
  metric: {
    flex: 1,
  },
  metricValue: {
    color: colors.text,
    fontFamily: fontFamily.bold,
    fontSize: 15,
  },
  metricLabel: {
    color: colors.textMuted,
    fontFamily: fontFamily.regular,
    fontSize: 12,
    marginTop: 3,
  },
  routeStores: {
    color: colors.textMuted,
    fontFamily: fontFamily.regular,
    fontSize: 14,
    marginTop: 16,
  },
  detailsSection: {
    borderTopColor: colors.border,
    borderTopWidth: StyleSheet.hairlineWidth,
    marginTop: 12,
    paddingTop: 24,
  },
  sectionTitle: {
    color: colors.text,
    fontFamily: fontFamily.bold,
    fontSize: 20,
  },
  detailHeading: {
    color: colors.text,
    fontFamily: fontFamily.bold,
    fontSize: 15,
    marginTop: 20,
  },
  storeRow: {
    alignItems: 'center',
    flexDirection: 'row',
    marginTop: 12,
  },
  storeNumber: {
    alignItems: 'center',
    backgroundColor: colors.primaryMuted,
    borderRadius: 14,
    color: colors.primary,
    fontFamily: fontFamily.bold,
    fontSize: 13,
    height: 28,
    justifyContent: 'center',
    overflow: 'hidden',
    textAlign: 'center',
    textAlignVertical: 'center',
    width: 28,
  },
  storeText: {
    flex: 1,
    marginLeft: 12,
  },
  storeName: {
    color: colors.text,
    fontFamily: fontFamily.bold,
    fontSize: 16,
  },
  storeAddress: {
    color: colors.textMuted,
    fontFamily: fontFamily.regular,
    fontSize: 13,
    marginTop: 2,
  },
  productGroup: {
    marginTop: 12,
  },
  productStore: {
    color: colors.textMuted,
    fontFamily: fontFamily.bold,
    fontSize: 14,
    marginBottom: 4,
  },
  productRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 32,
  },
  productName: {
    color: colors.text,
    flex: 1,
    fontFamily: fontFamily.regular,
    fontSize: 15,
    marginRight: 16,
  },
  productPrice: {
    color: colors.textMuted,
    fontFamily: fontFamily.regular,
    fontSize: 14,
  },
  requestedItem: {
    color: colors.text,
    fontFamily: fontFamily.regular,
    fontSize: 15,
    marginTop: 8,
  },
  mapButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    justifyContent: 'center',
    marginTop: 24,
    minHeight: 48,
    paddingHorizontal: 16,
  },
  mapButtonText: {
    color: colors.textInverse,
    fontFamily: fontFamily.bold,
    fontSize: 16,
  },
  stateTitle: {
    color: colors.text,
    fontFamily: fontFamily.bold,
    fontSize: 20,
  },
  stateText: {
    color: colors.textMuted,
    fontFamily: fontFamily.regular,
    fontSize: 15,
    lineHeight: 22,
    marginTop: 8,
    textAlign: 'center',
  },
  retryButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    justifyContent: 'center',
    marginTop: 20,
    minHeight: 48,
    paddingHorizontal: 20,
  },
  retryButtonText: {
    color: colors.textInverse,
    fontFamily: fontFamily.bold,
    fontSize: 16,
  },
});
