import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  content: {
    flex: 1,
    paddingHorizontal: 20,
    paddingVertical: 16,
  },
  heading: {
    color: '#1F2933',
    fontSize: 24,
    fontWeight: '600',
    marginBottom: 4,
  },
  supportingText: {
    color: '#52606D',
    fontSize: 15,
    marginBottom: 16,
  },
  newListButton: {
    alignItems: 'center',
    backgroundColor: '#243B53',
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 48,
    marginBottom: 16,
  },
  newListButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  savePanel: {
    borderBottomColor: '#D9E2EC',
    borderBottomWidth: StyleSheet.hairlineWidth,
    marginBottom: 16,
    paddingBottom: 16,
  },
  sectionTitle: {
    color: '#334E68',
    fontSize: 17,
    fontWeight: '600',
    marginBottom: 8,
  },
  listNameInput: {
    borderColor: '#9AA5B1',
    borderRadius: 8,
    borderWidth: 1,
    color: '#1F2933',
    fontSize: 16,
    minHeight: 44,
    paddingHorizontal: 12,
  },
  collectionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 10,
  },
  collectionButton: {
    borderColor: '#9AA5B1',
    borderRadius: 8,
    borderWidth: 1,
    minHeight: 36,
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  collectionButtonSelected: {
    backgroundColor: '#334E68',
    borderColor: '#334E68',
  },
  collectionButtonText: {
    color: '#334E68',
    fontSize: 14,
    fontWeight: '500',
  },
  collectionButtonTextSelected: {
    color: '#FFFFFF',
  },
  collectionInputRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 10,
  },
  collectionInput: {
    borderColor: '#9AA5B1',
    borderRadius: 8,
    borderWidth: 1,
    color: '#1F2933',
    flex: 1,
    fontSize: 15,
    minHeight: 44,
    paddingHorizontal: 12,
  },
  secondaryButton: {
    alignItems: 'center',
    backgroundColor: '#D9E2EC',
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: 12,
  },
  secondaryButtonText: {
    color: '#243B53',
    fontSize: 14,
    fontWeight: '600',
  },
  saveButton: {
    alignItems: 'center',
    backgroundColor: '#E8F1F5',
    borderRadius: 8,
    justifyContent: 'center',
    marginTop: 10,
    minHeight: 44,
  },
  saveButtonText: {
    color: '#243B53',
    fontSize: 15,
    fontWeight: '600',
  },
  savedListRows: {
    gap: 8,
    marginTop: 12,
  },
  savedListRow: {
    alignItems: 'center',
    borderColor: '#D9E2EC',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    minHeight: 52,
    paddingHorizontal: 12,
  },
  savedListCopy: {
    flex: 1,
  },
  savedListName: {
    color: '#243B53',
    fontSize: 15,
    fontWeight: '600',
  },
  savedListDetails: {
    color: '#7B8794',
    fontSize: 13,
    marginTop: 2,
  },
  loadText: {
    color: '#334E68',
    fontSize: 14,
    fontWeight: '600',
  },
  inputRow: {
    flexDirection: 'row',
    gap: 8,
  },
  input: {
    flex: 1,
    minHeight: 48,
    borderColor: '#9AA5B1',
    borderRadius: 8,
    borderWidth: 1,
    color: '#1F2933',
    fontSize: 16,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  button: {
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    paddingHorizontal: 16,
  },
  addButton: {
    backgroundColor: '#334E68',
  },
  primaryButton: {
    backgroundColor: '#243B53',
    marginTop: 16,
  },
  buttonDisabled: {
    opacity: 0.45,
  },
  buttonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  feedbackText: {
    color: '#B42318',
    fontSize: 14,
    marginTop: 8,
  },
  list: {
    flex: 1,
    marginTop: 20,
  },
  listContent: {
    flexGrow: 1,
  },
  item: {
    minHeight: 52,
    alignItems: 'center',
    borderBottomColor: '#D9E2EC',
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 8,
  },
  itemText: {
    color: '#1F2933',
    flex: 1,
    fontSize: 16,
    marginRight: 12,
  },
  removeButton: {
    minHeight: 44,
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  removeButtonText: {
    color: '#9B2C2C',
    fontSize: 15,
    fontWeight: '500',
  },
  emptyState: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  emptyTitle: {
    color: '#334E68',
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 6,
    textAlign: 'center',
  },
  emptyText: {
    color: '#7B8794',
    fontSize: 15,
    textAlign: 'center',
  },
  loadingContent: {
    flexDirection: 'row',
    gap: 8,
  },
});
