import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: {
    backgroundColor: '#F7F9F6',
    flex: 1,
  },
  content: {
    paddingBottom: 32,
    paddingHorizontal: 18,
    paddingTop: 18,
  },
  centeredState: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    padding: 24,
  },
  stateText: {
    color: '#52606D',
    fontSize: 15,
    marginTop: 12,
  },
  header: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    marginBottom: 18,
  },
  headerCopy: {
    flex: 1,
  },
  heading: {
    color: '#17231A',
    fontSize: 26,
    fontWeight: '700',
  },
  supportingText: {
    color: '#667168',
    fontSize: 15,
    lineHeight: 21,
    marginTop: 4,
  },
  newButton: {
    alignItems: 'center',
    backgroundColor: '#173F24',
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: 14,
  },
  newButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
  },
  section: {
    borderBottomColor: '#DCE3DC',
    borderBottomWidth: StyleSheet.hairlineWidth,
    paddingBottom: 20,
    paddingTop: 18,
  },
  sectionTitle: {
    color: '#294E34',
    fontSize: 17,
    fontWeight: '700',
    marginBottom: 10,
  },
  errorBanner: {
    alignItems: 'center',
    backgroundColor: '#FFF4ED',
    borderColor: '#F0B89A',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    marginBottom: 10,
    padding: 12,
  },
  errorText: {
    color: '#9A3412',
    flex: 1,
    fontSize: 14,
    lineHeight: 20,
  },
  retryButton: {
    minHeight: 36,
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  retryButtonText: {
    color: '#7C2D12',
    fontSize: 14,
    fontWeight: '700',
  },
  successText: {
    backgroundColor: '#E8F5E9',
    borderRadius: 8,
    color: '#166534',
    fontSize: 14,
    marginBottom: 10,
    padding: 12,
  },
  emptyListsText: {
    color: '#667168',
    fontSize: 14,
    paddingVertical: 8,
  },
  savedListRows: {
    gap: 8,
  },
  savedListRow: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#DCE3DC',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    minHeight: 58,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  savedListRowSelected: {
    borderColor: '#245C36',
    borderWidth: 2,
  },
  rowPressed: {
    backgroundColor: '#EEF5EC',
  },
  savedListCopy: {
    flex: 1,
  },
  savedListName: {
    color: '#17231A',
    fontSize: 15,
    fontWeight: '700',
  },
  savedListDetails: {
    color: '#667168',
    fontSize: 13,
    marginTop: 3,
  },
  loadText: {
    color: '#245C36',
    fontSize: 14,
    fontWeight: '700',
    marginLeft: 12,
  },
  loadingText: {
    color: '#52606D',
    fontSize: 14,
    marginTop: 10,
  },
  listNameInput: {
    backgroundColor: '#FFFFFF',
    borderColor: '#9AA5B1',
    borderRadius: 8,
    borderWidth: 1,
    color: '#17231A',
    fontSize: 16,
    minHeight: 48,
    paddingHorizontal: 12,
  },
  itemInputRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 12,
  },
  itemInput: {
    backgroundColor: '#FFFFFF',
    borderColor: '#9AA5B1',
    borderRadius: 8,
    borderWidth: 1,
    color: '#17231A',
    flex: 1,
    fontSize: 16,
    minHeight: 48,
    paddingHorizontal: 12,
  },
  addButton: {
    alignItems: 'center',
    backgroundColor: '#334E3C',
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 16,
  },
  addButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
  },
  suggestions: {
    backgroundColor: '#FFFFFF',
    borderColor: '#DCE3DC',
    borderRadius: 8,
    borderWidth: 1,
    marginTop: 8,
    overflow: 'hidden',
  },
  suggestion: {
    alignItems: 'center',
    borderBottomColor: '#E7ECE6',
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 44,
    paddingHorizontal: 12,
  },
  suggestionText: {
    color: '#17231A',
    fontSize: 15,
    fontWeight: '600',
  },
  suggestionDefault: {
    color: '#667168',
    fontSize: 13,
  },
  itemErrorText: {
    color: '#B42318',
    fontSize: 14,
    marginTop: 8,
  },
  itemRows: {
    marginTop: 14,
  },
  emptyItems: {
    alignItems: 'center',
    backgroundColor: '#EEF3ED',
    borderRadius: 8,
    minHeight: 112,
    justifyContent: 'center',
    padding: 20,
  },
  emptyTitle: {
    color: '#344A3A',
    fontSize: 17,
    fontWeight: '700',
  },
  emptyText: {
    color: '#667168',
    fontSize: 14,
    marginTop: 4,
  },
  itemRow: {
    alignItems: 'center',
    borderBottomColor: '#DCE3DC',
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    minHeight: 58,
    paddingVertical: 8,
  },
  itemCopy: {
    flex: 1,
  },
  itemName: {
    color: '#17231A',
    fontSize: 16,
    fontWeight: '600',
  },
  itemDetails: {
    color: '#667168',
    fontSize: 13,
    marginTop: 3,
  },
  removeButton: {
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: 8,
  },
  removeButtonText: {
    color: '#9B2C2C',
    fontSize: 14,
    fontWeight: '600',
  },
  actionRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 18,
  },
  deleteButton: {
    alignItems: 'center',
    borderColor: '#B42318',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 16,
  },
  deleteButtonText: {
    color: '#B42318',
    fontSize: 15,
    fontWeight: '700',
  },
  saveButton: {
    alignItems: 'center',
    backgroundColor: '#173F24',
    borderRadius: 8,
    flex: 1,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 16,
  },
  saveButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
  buttonDisabled: {
    opacity: 0.45,
  },
});
